version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: learn-postgres
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: Xby6d4g3
      POSTGRES_DB: ymdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - etl_network

  etl:
    image: ym_etl:latest
    container_name: ym_etl
    tty: true                           
    stdin_open: true 
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      YM_API_KEY: ${YM_API_KEY}
      YM_BUSINESS_ID: ${YM_BUSINESS_ID}
      YM_CAMPAIGN_ID: ${YM_CAMPAIGN_ID}
      LOG_LEVEL: INFO
    depends_on:
      - postgres
    networks:
      - etl_network
networks:
  etl_network:
    driver: bridge
volumes:
  postgres-data:
